// This is a data reference file, blobs field shouldn't be set on actual entities
models = {
	user: {
		_id: "US_" + random_string(29),
		created: new Date(),
		updated: new Date(),
		a_rand: (Dev && 25) || 500,
		name: "",
		email: [],
		password: "",
		credits: 0,
		banned: false,
		referrer: "",
		timezone: 0,
		cash: 0,
		worth: 0,
		language: "en",
		platform: "",
		pid: "",
		guild: "",
		server: "",
		friends: [],
		last_online: new Date(),
		cli_time: null,
		to_backup: false,
		popularity: 0.0,
		info: {},
		blobs: ["info"],
		post: post_get_init_user,
	},
	character: {
		_id: "CH_" + random_string(29),
		created: new Date(),
		updated: new Date(),
		a_rand: (Dev && 25) || 500,
		realm: "main",
		name: "",
		type: "",
		level: 1,
		worth: 0,
		xp: 0,
		owner: "",
		referrer: "",
		platform: "",
		pid: "",
		online: false,
		server: "",
		guild: "",
		friends: [],
		last_sync: new Date(),
		last_online: new Date(),
		to_backup: false,
		popularity: 0.0,
		private: false,
		info: {},
		blobs: ["info"],
		post: post_get_init_character,
	},
	guild: {
		_id: "GU_" + random_string(29),
		created: new Date(),
		updated: new Date(),
		a_rand: (Dev && 25) || 500,
		realm: "main",
		name: "",
		short: "",
		members: [],
		server: "",
		last_sync: new Date(),
		to_backup: false,
		popularity: 0.0,
		info: {},
		blobs: ["info"],
	},
	pet: {
		_id: "PT_" + random_string(29),
		created: new Date(),
		updated: new Date(),
		a_rand: (Dev && 25) || 500,
		realm: "main",
		name: "",
		type: "",
		level: 1,
		worth: 0,
		xp: 0,
		owner: "",
		online: false,
		server: "",
		last_sync: new Date(),
		last_online: new Date(),
		to_backup: false,
		info: {},
		blobs: ["info"],
	},
	server: {
		_id: "SR_EUI",
		created: new Date(),
		updated: new Date(),
		online: false,
		gameplay: "normal",
		realm: "main",
		name: "I",
		region: "EU",
		actual_ip: "0.0.0.0",
		ip: "0.0.0.0",
		port: 7192,
		version: "100",
		last_update: new Date(),
		info: {},
		blobs: ["info"],
	},
	message: {
		_id: "MS_" + random_string(29),
		created: new Date(),
		owner: "",
		author: "",
		fro: "",
		to: [],
		type: "",
		server: "",
		info: {},
		blobs: ["info"],
	},
	mail: {
		_id: "ML_" + random_string(29),
		created: new Date(),
		owner: [],
		read: false,
		item: false,
		taken: false,
		fro: "",
		to: "",
		type: "",
		info: {},
		blobs: ["info"],
	},
	event: {
		_id: "EV_" + random_string(29),
		created: new Date(),
		expire_at: null,
		tag: [],
		item_id: "",
		type: "",
		info: {},
		blobs: ["info"],
	},
	backup: {
		_id: "BC_" + random_string(29),
		model: "",
		backed: new Date(),
	},
	map: {
		_id: "MP_main",
		name: "main",
		created: new Date(),
		updated: new Date(),
		player: false,
		info: {},
		blobs: ["info"],
	},
	infoelement: {
		_id: "IE_main",
		created: new Date(),
		info: {},
		blobs: ["info"],
	},
	upload: {
		_id: "UL_" + random_string(29),
		created: new Date(),
		type: "photo",
		info: {},
		blobs: ["info"],
	},
	ip: {
		_id: "IP_0.0.0.0",
		created: new Date(),
		users: [],
		characters: [],
		random_id: "",
		referrer: "",
		exception: false,
		last_exception: null,
		info: {},
		blobs: ["info"],
	},
	mark: {
		_id: "MK_keyword",
	},
};
