var events={
	"abtesting":{
		"name":"A/B Testing",
		"modal":"event-abtesting",
		"sprite":"thehelmet",
		"duration":8*60,
		"join":true,
		"type":"daily",
	},
	"goobrawl":{
		"name":"Goo Brawl",
		"modal":"event-goobrawl",
		"sprite":"rgoo",
		"duration":9*60,
		"join":true,
		"type":"daily",
	},
	"crabxx":{
		"name":"Giga Crab",
		"modal":"event-crabxx",
		"sprite":"crabxx",
		"duration":60*40,
		"join":true,
		"type":"daily",
	},
	"franky":{
		"name":"Franky",
		"modal":"event-franky",
		"sprite":"franky",
		"duration":60*40,
		"join":true,
		"type":"nightly",
	},
	"icegolem":{
		"name":"Ice Golem",
		"modal":"event-icegolem",
		"sprite":"icegolem",
		"duration":60*40,
		"join":true,
		"type":"nightly",
	},
	"holidayseason":{
		"name":"Holiday Season",
		"modal":"event-holidayseason",
		"sprite":"grinch",
		"duration":60*60*24*30,
		//"join":true,
		"type":"seasonal",
	},
	"lunarnewyear":{
		"name":"Lunar New Year",
		"modal":"event-lunarnewyear",
		"sprite":"redenvelopev4",
		"duration":60*60*24*15,
		//"join":true,
		"type":"seasonal",
	},
	"valentines":{
		"name":"Valentines",
		"modal":"event-valentines",
		"sprite":"cupid",
		"duration":60*60*24*10,
		//"join":true,
		"type":"seasonal",
	},
	"egghunt":{
		"name":"Egg Hunt",
		"modal":"event-egghunt",
		"sprite":"basketofeggs",
		"duration":60*60*24*15,
		//"join":true,
		"type":"seasonal",
	},
	"halloween":{
		"name":"Halloween",
		"modal":"event-halloween",
		"sprite":"candy0",
		"duration":60*60*24*30,
		//"join":true,
		"type":"seasonal",
	},
};
