var events={
	"abtesting":{
		"name":"การทดสอบ A/B",
		"modal":"event-abtesting",
		"sprite":"thehelmet",
		"duration":8*60,
		"join":true,
		"type":"daily",
	},
	"goobrawl":{
		"name":"ศึกวุ้นธาตุ",
		"modal":"event-goobrawl",
		"sprite":"rgoo",
		"duration":9*60,
		"join":true,
		"type":"daily",
	},
	"crabxx":{
		"name":"ปูยักษ์",
		"modal":"event-crabxx",
		"sprite":"crabxx",
		"duration":60*40,
		"join":true,
		"type":"daily",
	},
	"franky":{
		"name":"แฟรงกี้",
		"modal":"event-franky",
		"sprite":"franky",
		"duration":60*40,
		"join":true,
		"type":"nightly",
	},
	"icegolem":{
		"name":"โกเลมน้ำแข็ง",
		"modal":"event-icegolem",
		"sprite":"icegolem",
		"duration":60*40,
		"join":true,
		"type":"nightly",
	},
	"holidayseason":{
		"name":"เทศกาลวันหยุด",
		"modal":"event-holidayseason",
		"sprite":"grinch",
		"duration":60*60*24*30,
		//"join":true,
		"type":"seasonal",
	},
	"lunarnewyear":{
		"name":"ตรุษจีน",
		"modal":"event-lunarnewyear",
		"sprite":"redenvelopev4",
		"duration":60*60*24*15,
		//"join":true,
		"type":"seasonal",
	},
	"valentines":{
		"name":"วันวาเลนไทน์",
		"modal":"event-valentines",
		"sprite":"cupid",
		"duration":60*60*24*10,
		//"join":true,
		"type":"seasonal",
	},
	"egghunt":{
		"name":"ล่าไข่",
		"modal":"event-egghunt",
		"sprite":"basketofeggs",
		"duration":60*60*24*15,
		//"join":true,
		"type":"seasonal",
	},
	"halloween":{
		"name":"ฮาโลวีน",
		"modal":"event-halloween",
		"sprite":"candy0",
		"duration":60*60*24*30,
		//"join":true,
		"type":"seasonal",
	},

	// M5.8 — Side Quest 8 อัน (บางระจัน)
	"quest_hunt_phayamon":{
		"name":"ล่าพญามอญ",
		"type":"quest",
		"reward":"งามอูฐมงคล",
		"target":"boss_phayamon",
		"description":"ออกล่าพญามอญ (เมืองตะนาวศรี) ที่ทุ่งราชพิลาส เพื่อนำงามอูฐมงคลกลับมา",
	},
	"quest_yantra_phr":{
		"name":"หาผ้ายันต์พระประโยชน์ผล",
		"type":"quest",
		"reward":"ผ้ายันต์พระประโยชน์ผล",
		"target":"wat_pho_kao_ton",
		"description":"เดินทางไปวัดโพธิ์เก้าตัน พบพระประโยชน์ผล เพื่อขอผ้ายันต์ที่ลงอักขระไว้",
	},
	"quest_rice_branrachan":{
		"name":"ส่งข้าวให้ทหาร",
		"type":"quest",
		"reward":"เบี้ยเงินเก่า ×500",
		"target":"qrice_branrachan",
		"goal":10,
		"description":"เก็บข้าวเปลือกบางระจัน 10 ถัง ส่งให้ทหารที่ค่าย",
	},
	"quest_repair_camp":{
		"name":"ซ่อมค่าย",
		"type":"quest",
		"reward":"เบี้ยเงินเก่า ×300",
		"target":"wood_log",
		"goal":50,
		"description":"ตัดไม้ซุง 50 ท่อน นำมาซ่อมกำแพงวัดโพธิ์เก้าตันที่ร้าว",
	},
	"quest_train_archer":{
		"name":"ฝึกธนู",
		"type":"quest",
		"reward":"ธนูไม้ไผ่ (ทอง)",
		"target":"target_dummy",
		"goal":60,
		"description":"ฝึกยิงธนูเป้า 60 ดอก — 20 ดอกแรก (เบสิค), 20 ดอกที่สอง (ระยะกลาง), 20 ดอกที่สาม (ยาก)",
	},
	"quest_craft_sword":{
		"name":"ตีดาบ",
		"type":"quest",
		"reward":"ดาบทองเหมาะ (legendary)",
		"target":"iron_ingot",
		"goal":5,
		"description":"ขุดเหล็กแท่ง 5 อันจากเหมืองเก่า นำไปให้นายบุญมาตีเป็นดาบ",
	},
	"quest_cross_battlefield":{
		"name":"ข้ามทุ่งราชพิลาส",
		"type":"quest",
		"reward":"ผ้ายันต์คงกระพัน",
		"target":"tung_rachaphi_lat",
		"description":"ข้ามทุ่งราชพิลาส ฝ่ากองทหารพม่า เพื่อส่งข่าวจากอยุธยาไปบางระจัน",
	},
	"quest_find_lan_br":{
		"name":"ตามหาใบลานศึกบางระจัน",
		"type":"quest",
		"reward":"ใบลานศึกบางระจัน",
		"target":"lan_document",
		"goal":3,
		"description":"ค้นหาใบลานจารึกเรื่องราวการสู้รบ 3 แผ่น จากสถานที่ต่างๆ เพื่อรวบรวมเป็นเอกสารประวัติศาสตร์",
	},
};
