var craft={
	"basketofeggs":{
		"items":[
			[1,"egg0"],
			[1,"egg1"],
			[1,"egg2"],
			[1,"egg3"],
			[1,"egg4"],
			[1,"egg5"],
			[1,"egg6"],
			[1,"egg7"],
			[1,"egg8"],
		],
		"cost":100,
	},
	"xbox":{
		"items":[
			[1,"x0"],
			[1,"x1"],
			[1,"x2"],
			[1,"x3"],
			[1,"x4"],
			[1,"x5"],
			[1,"x6"],
			[1,"x7"],
			[1,"x8"],
		],
		"cost":1200,
	},
	"carrotsword":{
		"items":[
			[1,"blade"],
			[1,"carrot"],
		],
		"cost":500,
	},
	"wblade":{
		"items":[
			[1,"stick",9],
			[1,"blade",9],
			[800,"essenceoffrost"],
		],
		"cost":24000000,
	},
	"rod":{
		"items":[
			[1,"staff"],
			[1,"spidersilk"],
		],
		"cost":100,
	},
	"pickaxe":{
		"items":[
			[1,"staff"],
			[1,"spidersilk"],
			[1,"blade"],
		],
		"cost":100,
	},
	"stealthcape":{
		"items":[
			[1,"bcape",7],
			[5,"shadowstone"],
			[200,"essenceofnature"],
			[1000,"cscale"],
		],
		"cost":2000000,
	},
	"cake":{
		"items":[
			[10,"whiteegg"],
		],
		"cost":5,
	},
	"bfangamulet":{
		"items":[
			[1,"bfang"],
			[5000,"bwing"],
		],
		"cost":4000000,
	},
	// "stand1":{
	// 	"items":[
	// 		[1,"stand0"],
	// 		[1,"ledger"],
	// 		[6,"storagebox"],
	// 	],
	// 	"cost":6400000,
	// },
	"wingedboots":{
		"items":[
			[1,"shoes"],
			[20,"feather0"],
		],
		"cost":120000,
	},
	"fierygloves":{
		"items":[
			[1,"gloves"],
			[20,"feather0"],
			[2,"essenceoffire"],
		],
		"cost":120000,
	},
	"fclaw":{
		"items":[
			[1,"claw"],
			[2,"essenceoffrost"],
		],
		"cost":20000,
	},
	"fsword":{
		"items":[
			[1,"blade"],
			[2,"essenceoffrost"],
		],
		"cost":20000,
	},
	"froststaff":{
		"items":[
			[1,"staff"],
			[2,"essenceoffrost"],
		],
		"cost":20000,
	},
	"snowflakes":{
		"items":[
			[1,"throwingstars"],
			[1,"essenceoffrost"],
		],
		"cost":20000,
	},
	"frostbow":{
		"items":[
			[1,"bow"],
			[3,"essenceoffrost"],
		],
		"cost":40000,
	},
	"firebow":{
		"items":[
			[1,"bow"],
			[1,"essenceoffire"], // Was 2 [2024/04/12]
		],
		"cost":20000, // Was 40000 [2024/04/12]
	},
	"fireblade":{
		"items":[
			[1,"blade"],
			[1,"essenceoffire"],
		],
		"cost":20000,
	},
	"firestaff":{
		"items":[
			[1,"staff"],
			[1,"essenceoffire"],
		],
		"cost":20000,
	},
	"firestars":{
		"items":[
			[1,"throwingstars"],
			[1,"essenceoffire"],
		],
		"cost":180000,
	},
	"heartwood":{
		"items":[
			[1,"woodensword",8],
			[1,"nheart"],
		],
		"cost":120000000,
	},
	"offeringx":{
		"items":[
			[10,"offering"],
			[1200,"essenceofnature"],
			[200,"essenceoflife"],
			[1,"essenceofgreed"],
		],
		"cost":32000000,
	},
	"computer":{
		"items":[
			[1,"networkcard"],
			[8,"qubics"],
			[1,"platinumnugget"],
			[12,"goldnugget"],
			[100,"electronics"],
		],
		"cost":120000000,
	},
	"supercomputer":{
		"items":[
			[1,"computer"],
			[1,"tracker"],
			[3,"qubics"],
			[2000,"electronics"],
		],
		"cost":4800000000,
	},
	"dartgun":{
		"items":[
			[1,"blade",9],
			[12,"qubics"],
			[4,"platinumnugget"],
			[20,"goldnugget"],
		],
		"cost":32000000,
	},
	"bronzeingot":{
		"items":[
			[16,"bronzenugget"],
		],
		"cost":360000,
	},
	"goldingot":{
		"items":[
			[12,"goldnugget"],
		],
		"cost":3600000,
	},
	"platinumingot":{
		"items":[
			[8,"platinumnugget"],
		],
		"cost":36000000,
	},
	"candycanesword":{
		"items":[
			[1,"blade",7],
			[1,"candycane"],
		],
		"cost":480000,
	},
	"merry":{
		"items":[
			[1,"bow"],
			[1,"candycane"],
			[1,"mistletoe"],
		],
		"cost":480000,
	},
	"harpybow":{
		"items":[
			[1,"t2bow"],
			[100,"feather1"],
		],
		"cost":1640000,
	},
	"gstaff":{
		"items":[
			[1,"staff",8],
			[1,"essenceofgreed"],
		],
		"cost":180000,
	},
	"pouchbow":{
		"items":[
			[1,"bow"],
			[1,"smoke"],
		],
		"cost":180000,
	},
	"ornamentstaff":{
		"items":[
			[1,"staff"],
			[1,"ornament"],
			[20,"confetti"],
		],
		"cost":120000,
	},
	"charmer":{
		"items":[
			[1,"goldnugget"],
			[20,"gem1"],
			[1,"emptyheart"],
		],
		"cost":80000,
	},
	"ctristone":{
		"items":[
			[1,"strring"],
			[1,"intring"],
			[1,"dexring"],
			[10,"vitscroll"],
		],
		"cost":20000,
	},
	"cclaw":{
		"items":[
			[1,"claw"],
			[1,"crabclaw"],
		],
		"cost":24000,
	},
	"slimestaff":{
		"items":[
			[1,"staff"],
			[10,"gslime"],
		],
		"cost":24000,
	},
	"mushroomstaff":{
		"items":[
			[1,"staff"],
			[2,"smush"],
		],
		"cost":24000,
	},
	"wcap":{
		"items":[
			[50,"beewings"],
			[3,"gslime"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"wgloves":{
		"items":[
			[60,"beewings"],
			[20,"spores"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"wbreeches":{
		"items":[
			[10,"crabclaw"],
			[100,"spores"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"wattire":{
		"items":[
			[100,"gslime"],
			[200,"crabclaw"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"wshoes":{
		"items":[
			[5,"frogt"],
			[500,"beewings"],
			[100,"crabclaw"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"quiver":{
		"items":[
			[1,"ascale"],
			[200,"beewings"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"orbg":{
		"items":[
			[1,"ascale"],
			[1,"pleather"],
			[1,"cscale"],
			[1,"bfur"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"orba":{
		"items":[
			[1,"orboffire"],
			[1,"orboffrost"],
			[1,"orbofplague"],
			[1,"orbofresolve"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"armorring":{
		"items":[
			[1,"snakefang"],
			[1,"lotusf"],
			[1,"vitring",2],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"resistancering":{
		"items":[
			[1,"ink"],
			[5,"ascale"],
			[1,"vitring",2],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"lbelt":{
		"items":[
			[100,"bfur"],
			[1,"hpbelt",2],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"stinger":{
		"items":[
			[12,"feather0"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"hbow":{
		"items":[
			[40,"dstones"],
			[2,"pleather"],
			[1,"feather0"],
		],
		"cost":0,
		"quest":"mcollector",
	},
	"snakeoil":{
		"items":[
			[40,"dstones"],
			[9000,"rattail"],
		],
		"cost":0,
		"quest":"witch",
	},
	"elixirfires":{
		"items":[
			[1,"cshell"],
			[2000,"hpot0"],
		],
		"cost":0,
		"quest":"witch",
	},
	"elixirfzres":{
		"items":[
			[50,"bfur"],
			[10,"mpot0"],
		],
		"cost":0,
		"quest":"witch",
	},
	"elixirpnres":{
		"items":[
			[500,"bwing"],
			[1,"hpot0"],
		],
		"cost":0,
		"quest":"witch",
	},
	"daggerofthedead":{
		"items":[
			[1,"mbones"],
			[1,"wand"],
		],
		"cost":24000,
	},
	"spearofthedead":{
		"items":[
			[2,"mbones"],
			[1,"spear"],
		],
		"cost":24000,
	},
	"staffofthedead":{
		"items":[
			[1,"mbones"],
			[1,"staff"],
		],
		"cost":120000,
	},
	"bowofthedead":{
		"items":[
			[1,"mbones"],
			[1,"bow"],
		],
		"cost":120000,
	},
	"swordofthedead":{
		"items":[
			[1,"mbones"],
			[1,"sword"],
		],
		"cost":24000,
	},
	"maceofthedead":{
		"items":[
			[1,"mbones"],
			[1,"wbasher"],
		],
		"cost":240000,
	},
	"pmaceofthedead":{
		"items":[
			[1,"mbones"],
			[1,"pmace"],
		],
		"cost":24000,
	},
    "weaver":{
		"items":[
			[1,"bow"],
			[30,"cocoon"],
		],
		"cost":75000,
	},
    "cocoon":{
		"items":[
			[1000,"spidersilk"],
		],
		"cost":2500,
	},
	"elixirint1":{"items":[[10,"elixirint0"]],"cost":1000},
	"elixirdex1":{"items":[[10,"elixirdex0"]],"cost":1000},
	"elixirvit1":{"items":[[10,"elixirvit0"]],"cost":1000},
	"elixirstr1":{"items":[[10,"elixirstr0"]],"cost":1000},
	"elixirint2":{"items":[[10,"elixirint1"]],"cost":2400},
	"elixirdex2":{"items":[[10,"elixirdex1"]],"cost":2400},
	"elixirvit2":{"items":[[10,"elixirvit1"]],"cost":2400},
	"elixirstr2":{"items":[[10,"elixirstr1"]],"cost":2400},
	"threadneedle":{
		"items":[
			[1,"blade",5],
			[20,"spidersilk"],
			[20,"ashleaf"],
		],
		"cost":120000,
	},
	"brinefang":{
		"items":[
			[1,"blade",7],
			[120,"reefglass"],
			[1,"cshell"],
		],
		"cost":180000,
	},
	"molehook":{
		"items":[
			[1,"pickaxe",5],
			[40,"gemfragment"],
			[2,"bronzenugget"],
		],
		"cost":90000,
	},
	"cinderwand":{
		"items":[
			[1,"wand",7],
			[1,"embercore"],
			[6,"essenceoffire"],
			[40,"ashleaf"],
		],
		"cost":240000,
	},
	"pollenbow":{
		"items":[
			[1,"bow",7],
			[60,"beewings"],
			[60,"ashleaf"],
			[10,"essenceofnature"],
		],
		"cost":90000,
	},
	"rimeknuckles":{
		"items":[
			[1,"claw",7],
			[1,"frostcore"],
			[12,"bfur"],
			[4,"essenceoffrost"],
		],
		"cost":180000,
	},
	"lanternshield":{
		"items":[
			[1,"shield",6],
			[1,"embercore"],
			[1,"bronzeingot"],
		],
		"cost":240000,
	},
	"turtleshard":{
		"items":[
			[1,"wshield",6],
			[80,"reefglass"],
			[1,"cshell"],
		],
		"cost":100000,
	},
	"ratkingbuckler":{
		"items":[
			[1,"wshield",4],
			[30,"rattail"],
			[20,"ashleaf"],
			[1,"bronzenugget"],
		],
		"cost":40000,
	},
	"stormquiver":{
		"items":[
			[1,"alloyquiver",5],
			[80,"stormfeather"],
			[8,"essenceofether"],
		],
		"cost":500000,
	},
	"thistlequiver":{
		"items":[
			[1,"quiver",5],
			[10,"pleather"],
			[40,"ashleaf"],
			[5,"essenceofnature"],
		],
		"cost":140000,
	},
	"scribeorb":{
		"items":[
			[1,"wbook0",3],
			[12,"voidthread"],
			[50,"bwing"],
			[4,"essenceofether"],
		],
		"cost":280000,
	},
	"mossheart":{
		"items":[
			[1,"wbook0",4],
			[2,"verdantcore"],
			[120,"ashleaf"],
			[80,"essenceofnature"],
		],
		"cost":800000,
	},
	"emberseal":{
		"items":[
			[1,"strring",2],
			[1,"embercore"],
			[6,"essenceoffire"],
		],
		"cost":300000,
	},
	"glacierseal":{
		"items":[
			[1,"intring",2],
			[1,"frostcore"],
			[6,"essenceoffrost"],
		],
		"cost":300000,
	},
	"venomband":{
		"items":[
			[1,"dexring",2],
			[1,"verdantcore"],
			[12,"poison"],
			[4,"snakefang"],
		],
		"cost":240000,
	},
	"saffronloop":{
		"items":[
			[1,"vitearring",2],
			[1,"goldnugget"],
			[100,"gemfragment"],
		],
		"cost":350000,
	},
	"moonshardearring":{
		"items":[
			[1,"intearring",2],
			[8,"voidthread"],
			[40,"bwing"],
			[4,"essenceofether"],
		],
		"cost":240000,
	},
	"cloverstud":{
		"items":[
			[1,"vitearring",2],
			[1,"verdantcore"],
			[40,"ashleaf"],
			[40,"spores"],
			[5,"gslime"],
		],
		"cost":280000,
	},
	"anchorbelt":{
		"items":[
			[1,"hpbelt",2],
			[150,"reefglass"],
			[1,"cshell"],
		],
		"cost":260000,
	},
	"windbelt":{
		"items":[
			[1,"dexbelt",2],
			[40,"stormfeather"],
			[4,"essenceofether"],
		],
		"cost":300000,
	},
	"knifebelt":{
		"items":[
			[1,"dexbelt",2],
			[30,"spidersilk"],
			[8,"voidthread"],
			[20,"bwing"],
			[12,"poison"],
		],
		"cost":350000,
	},
	"gloampendant":{
		"items":[
			[1,"dexamulet",2],
			[12,"voidthread"],
			[80,"bwing"],
			[6,"essenceofether"],
		],
		"cost":420000,
	},
	"worldrootcrook":{
		"items":[
			[1,"harbringer",8],
			[1,"sapstone"],
			[1,"platinumingot"],
			[3,"goldingot"],
			[4,"ijx"],
			[12,"ectoplasm"],
			[1,"bcandle"],
		],
		"cost":250000000,
	},
	"emberhood":{
		"items":[
			[1,"mmhat",5],
			[1,"embercore"],
			[8,"essenceoffire"],
			[20,"ashleaf"],
		],
		"cost":400000,
	},
	"bogcrown":{
		"items":[
			[1,"helmet",7],
			[1,"verdantcore"],
			[12,"poison"],
			[40,"ashleaf"],
		],
		"cost":220000,
	},
	"ratworkcoat":{
		"items":[
			[1,"coat",5],
			[30,"rattail"],
			[40,"ashleaf"],
		],
		"cost":75000,
	},
	"reefvest":{
		"items":[
			[1,"coat1",7],
			[200,"reefglass"],
			[2,"cshell"],
		],
		"cost":400000,
	},
	"silkgrips":{
		"items":[
			[1,"gloves",5],
			[30,"spidersilk"],
			[8,"voidthread"],
			[20,"bwing"],
		],
		"cost":120000,
	},
	"thundergrips":{
		"items":[
			[1,"mrngloves",6],
			[80,"stormfeather"],
			[12,"essenceofether"],
		],
		"cost":800000,
	},
	"bogwalkers":{
		"items":[
			[1,"shoes1",6],
			[1,"verdantcore"],
			[12,"poison"],
			[8,"snakefang"],
		],
		"cost":260000,
	},
	"cinderboots":{
		"items":[
			[1,"shoes1",6],
			[1,"embercore"],
			[8,"essenceoffire"],
			[20,"ashleaf"],
		],
		"cost":280000,
	},
	"rimeboots":{
		"items":[
			[1,"shoes1",6],
			[1,"frostcore"],
			[8,"essenceoffrost"],
			[12,"bfur"],
		],
		"cost":280000,
	},
	"reedpants":{
		"items":[
			[1,"pants",6],
			[20,"frogt"],
			[4,"lotusf"],
			[40,"ashleaf"],
		],
		"cost":100000,
	},
	"beastmantle":{
		"items":[
			[1,"cape",7],
			[2,"verdantcore"],
			[240,"leather"],
		],
		"cost":1200000,
	},
	"starcloak":{
		"items":[
			[1,"cape",7],
			[40,"voidthread"],
			[40,"essenceofether"],
			[1,"platinumnugget"],
		],
		"cost":1800000,
	},
};

var dismantle={
	"daggerofthedead":{
		"items":[
			[1,"mbones"],
		],
		"cost":40,
	},
	"swordofthedead":{
		"items":[
			[1,"mbones"],
		],
		"cost":40,
	},
	"staffofthedead":{
		"items":[
			[1,"mbones"],
		],
		"cost":40,
	},
	"bowofthedead":{
		"items":[
			[1,"mbones"],
		],
		"cost":40,
	},
	"maceofthedead":{
		"items":[
			[1,"mbones"],
		],
		"cost":40,
	},
	"pmaceofthedead":{
		"items":[
			[1,"mbones"],
		],
		"cost":40,
	},
	"spearofthedead":{
		"items":[
			[2,"mbones"],
		],
		"cost":40,
	},
	"fireblade":{
		"items":[
			[1,"essenceoffire"],
		],
		"cost":10000,
	},
	"firebow":{  // Added firebow [2024/04/12]
		"items":[
			[1,"essenceoffire"],
		],
		"cost":10000,
	},
	"firestaff":{
		"items":[
			[1,"essenceoffire"],
		],
		"cost":10000,
	},
	"firestars":{
		"items":[
			[1,"essenceoffire"],
		],
		"cost":10000,
	},
	"essenceoffrost":{
		"items":[
			[1,"emptyjar"],
		],
		"cost":10,
	},
	"essenceoflife":{
		"items":[
			[1,"emptyjar"],
		],
		"cost":10,
	},
	"essenceoffire":{
		"items":[
			[1,"emptyjar"],
		],
		"cost":10,
	},
	"essenceofnature":{
		"items":[
			[1,"emptyjar"],
		],
		"cost":10,
	},
	"bronzeingot":{
		"items":[
			[16,"bronzenugget"],
		],
		"cost":120000,
	},
	"goldingot":{
		"items":[
			[12,"goldnugget"],
		],
		"cost":1200000,
	},
	"platinumingot":{
		"items":[
			[8,"platinumnugget"],
		],
		"cost":12000000,
	},
	"lostearring":{
		"items":[
			[0.12,"goldnugget"],
		],
		"cost":36000,
	},
	"goldenegg":{
		"items":[
			[1,"goldnugget"],
			[0.5,"goldnugget"],
		],
		"cost":120000,
	},
	"molesteeth":{
		"items":[
			[0.1,"platinumnugget"],
		],
		"cost":100000,
	},
	// "ringsj":{
	// 	"items":[
	// 		[1,"wshield"],
	// 		[1,"wshield"],
	// 	],
	// 	"cost":100000,
	// },
	// "offering":{
	// 	"items":[
	// 		[1,"emptyjar"],
	// 	],
	// 	"cost":20,
	// },
};
